### ISSUE TITLE
fix README

### ISSUE THREAD

**Issue by nlyubova** [ros-naoqi/naoqi_bridge#49]
change the link to http://wiki.ros.org/nao

**Comment by vrabaud** [comment]
You know that you can edit the file in GitHub and that will create a PR automatically when you don't have commit access, right ? Please do so that you train :) Top right of https://github.com/ros-naoqi/naoqi_bridge/blob/master/README.md you have: edit this file.

**Comment by nlyubova** [comment]
thank you! done it

**Comment by vrabaud** [comment]
GitHub is so cool :)
